# Generated by Django 3.0.1 on 2020-02-03 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_number', models.CharField(max_length=100, unique=True)),
                ('fscore', models.IntegerField(blank=True, max_length=2)),
                ('sscore', models.IntegerField(blank=True, max_length=2)),
                ('cscore', models.IntegerField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MYclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=10, unique=True)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('t', 'معلم')], default='t', help_text='نوع', max_length=1)),
                ('date_registered', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 17, 56, 54, 501324))),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=9, unique=True)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('isactive', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='accounts.course')),
                ('myclass', models.ManyToManyField(to='accounts.MYclass')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('s', 'دانش آموز')], default='s', help_text='نوع', max_length=1)),
                ('date_registered', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 17, 56, 54, 503319))),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('user_name', models.CharField(max_length=9, unique=True)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('Grade', models.CharField(blank=True, max_length=100)),
                ('my_parent', models.CharField(max_length=30, unique=True)),
                ('isactive', models.BooleanField(default=False)),
                ('myclass', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='accounts.MYclass')),
                ('taken_courses', models.ManyToManyField(to='accounts.course')),
                ('teachers', models.ManyToManyField(to='accounts.teacher')),
            ],
        ),
    ]
