# Generated by Django 3.0.1 on 2020-02-08 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200208_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 8, 2, 57, 54, 76784))),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 8, 2, 57, 54, 76784)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 8, 2, 57, 54, 61160)),
        ),
    ]
