# Generated by Django 3.0.1 on 2020-02-08 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200208_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadline',
            old_name='day',
            new_name='chday',
        ),
        migrations.RenameField(
            model_name='deadline',
            old_name='hour',
            new_name='phday',
        ),
        migrations.AddField(
            model_name='deadline',
            name='chhour',
            field=models.IntegerField(blank=True, default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='deadline',
            name='phhour',
            field=models.IntegerField(blank=True, default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='deadline',
            name='rday',
            field=models.IntegerField(blank=True, default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='deadline',
            name='rhour',
            field=models.IntegerField(blank=True, default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 8, 3, 10, 55, 83632)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 8, 3, 10, 55, 68008)),
        ),
    ]
