# Generated by Django 2.2 on 2020-06-01 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200601_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='chday',
            field=models.IntegerField(blank=True, default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='chhour',
            field=models.IntegerField(blank=True, default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='phday',
            field=models.IntegerField(blank=True, default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='phhour',
            field=models.IntegerField(blank=True, default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='rday',
            field=models.IntegerField(blank=True, default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='rhour',
            field=models.IntegerField(blank=True, default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 1, 14, 2, 54, 980532)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 1, 14, 2, 54, 980532)),
        ),
    ]
